// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwfciyizrpejxsspivca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3ZmNpeWl6cnBlanhzc3BpdmNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MTE0NzIsImV4cCI6MjA2NTM4NzQ3Mn0.IWCrV1Nb5xU_05Ju8p_epydtDeyIHqPltOLbrXaDHhs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);